# <center> LESSON 4: Introduction to NUMPY </center>


![](https://gradfutures.princeton.edu/sites/gradprofdev/files/events/numpylogo_-_gabe_perez-giz.png)

## 1.INTRODUCTION

**NumPY** (Numerical Python) = multidimensional array + matrix data structure

### 1.1 Installation

- Install when creating a virtual/conda enviroment
```
conda create -n h.minh python=3.7 numpy pandas
```
- Install via conda or pip 
```
or
```
pip install numpy


In [1]:
 !pip install numpy

In [4]:
!pip install scikit-learn 

### 1.2 Import

In [2]:
import numpy as np

### 1.3 Why Numpy

In [7]:
ar = np.array([1,2,3])
ar1 = np.array([2,3,4])
ar + ar1

array([3, 5, 7])

- broadcasting 

![](https://i.stack.imgur.com/JcKv1.png)

# 2. BASICS

`ndarray` = N-dimensional array

- 0-D array: Scalar
- 1-D array: Vector
- 2-D array: Matrix
- 3-D array: Tensor

### 2.1 Create an array

`np.array()`

In [7]:
li = [1, 2.14, 'str']
li

[1, 2.14, 'str']

In [5]:
ar = np.array([1, 2, 3])
type(ar[0]), type(ar[1]), type(ar[2])

(numpy.int32, numpy.int32, numpy.int32)

In [8]:
ar1 = np.array(li) #casting into 1 type
ar1

array(['1', '2.14', 'str'], dtype='<U32')

In [9]:
def addition(a,b):
    '''
    sum of 2 numbers
    
    parameters
    a: first number
    b: second number
    '''
    return a+b

In [10]:
addition

<function __main__.addition(a, b)>

In [3]:
ar1 = np.array([[1, 2, 4],
               [2, 3, 4]]) #array 1 dimension wwith 3 elements

In [16]:
ar1.ndim

2

In [17]:
ar1.shape #dimension+elements per dimension

(2, 3)

In [18]:
len(ar1)

2

In [19]:
ar1.size

6

beside `np.array()`, we use `np.zeros()`, `np.ones`, `np.arange`, `np.linspace`

In [7]:
np.zeros(shape=3)

array([0., 0., 0.])

In [8]:
np.zeros(shape=[3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
np.full(3,'mci')

array(['mci', 'mci', 'mci'], dtype='<U3')

In [ ]:
np.arange 