In [7]:
import numpy as np

### Create a new array of 3*2 float numbers, filled with ones.

In [5]:
np.ones((3,2), dtype = float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let `x = np.arange(4, dtype=np.int64)`. Create an array of ones with the same shape and type as X.
Hint: uses `np.ones_like()`

In [7]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1], dtype=int64)

### Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.
### Hint: use `np.zeros_like()`

In [8]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0], dtype=int64)

### Create a new array of shape 2*5 , filled with 6.

In [9]:
np.full((2,5), 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

### Create an array of [1, 2, 3].

In [11]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

### Let x = [1, 2]. Convert it into an array.
### Hint: use `np.asarray()`

In [16]:
x = [1,2]
np.asarray(x)

array([1, 2])

### Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.
### Hint: use `np.asmatrix()`

In [21]:
X1 = np.array([[1, 2], [3, 4]])
X = np.array([[1, 2], [3, 4]])
np.asmatrix(X)
X1

array([[1, 2],
       [3, 4]])

### Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.
### Hint: use `x.item()` or `x[0]`

In [22]:
x = np.array([30])
x.item(0)

30

In [23]:
x[0]

30

### Create an array of 2, 4, 6, 8, ..., 100.

In [8]:
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.
### Hint: use `np.linspace()`

In [9]:
np.linspace(3,10, dtype=float)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

### Create a 1-D array of 50 element spaced evenly between 3. and 10., exclude 10.
### Hint: add parameter `endpoint=False`

In [28]:
np.linspace(3,10, dtype=float, endpoint = False)

array([3.  , 3.14, 3.28, 3.42, 3.56, 3.7 , 3.84, 3.98, 4.12, 4.26, 4.4 ,
       4.54, 4.68, 4.82, 4.96, 5.1 , 5.24, 5.38, 5.52, 5.66, 5.8 , 5.94,
       6.08, 6.22, 6.36, 6.5 , 6.64, 6.78, 6.92, 7.06, 7.2 , 7.34, 7.48,
       7.62, 7.76, 7.9 , 8.04, 8.18, 8.32, 8.46, 8.6 , 8.74, 8.88, 9.02,
       9.16, 9.3 , 9.44, 9.58, 9.72, 9.86])

Lex x be an array  
`[[ 1 2 3],
[ 4 5 6]]`.

and y be an array  
`[[ 7 8 9],
[10 11 12]]`.

Concatenate x and y so that a new array looks like  
`[[1, 2, 3, 7, 8, 9],
[4, 5, 6, 10, 11, 12]]`.

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
np.concatenate((x,y), axis = 1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Concatenate x and y so that a new array looks like  
`[[ 1  2  3],
 [ 4  5  6],
 [ 7  8  9],
 [10 11 12]]`.

In [14]:
np.concatenate((x,y), axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [15]:
x = np.arange(1,10,1)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr1 = x[0:4]
arr1

array([1, 2, 3, 4])

In [20]:
arr2 = x[4:6]
arr2

array([5, 6])

In [21]:
arr3 = x[6:10]
arr3

array([7, 8, 9])